### ISSUE TITLE
Bot not posting

### ISSUE THREAD

**Issue by ThatOneTraitor** [110Percent/BeeBot#2]
When i post "Bee Movie script, please.", the command prompt recognises that ive posted something but  just shows this error for every line posted.

(node:11828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Unauthorized

**Comment by aurieh** [comment]
Discord.JS v8 is outdated, you must prefix your token with `Bot ` manually (note the space).

**Comment by aurieh** [comment]
@110Percent pls close this, or better, update your code to D.JS v11;

**Comment by ThatOneTraitor** [comment]
How would i prefix it? sorry im not that good when it comes to coding or stuff like that

**Comment by aurieh** [comment]
`Bot INSERT_YOUR_TOKEN_HERE` should be the token

**Comment by 110Percent** [comment]
Will update to d.js 11.
